### PR TITLE
Updated project structure and .gitignore

### PR DESCRIPTION
**Pull request by nfreundlich**
Hi Hannah,

I've created basic project structure and committed it to my branch.
Also, created the .gitignore file, which helps us avoid unnecessary files to be tracked by git (eg. all the venv folder for pycharm etc).

So I'm testing this first 'pull request'  and added you as a reviewer - can you see it? You can comment, approve, etc.

Norbert

### CODE REVIEW

**Comment by hewilder** [comment]
I got an email when you submitted the pull request so I think this will work.

**Comment by hewilder** [comment]
Do you have a preference on what kind of pull request merging we use?

**Comment by nfreundlich** [comment]
Well, never used "Squash and merge" but might be useful: we lose individual commits from a 'feature' (personal) branch after merging but we keep the 'dev' branch clean. I'm good to try it.

Got the info here:
https://blog.github.com/2016-04-01-squash-your-commits/

**Comment by hewilder** [comment]
Testing out the squash merge.

**Pull request merged**
